FROM maven:3.8.4-openjdk-21 AS build

#set the working directory
WORKDIR /app

@copy the pom.xml and install dependencies
COPY pom.xml .
RUN mvn dependency:go-offline


#copy the source code and build the application
COPY src ./src
RUN mvn clean package -DskipTests

#use an official openjdk image to run the application
FROM openjdk:21-jdk-slim


#  set the working directory
WORKDIR /app

#copy the build jAR file from the build stage
COPY --from==build /app/target/