FROM maven:3.9.4-eclipse-temurin-21-alpine AS build
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:21-slim
COPY --from=build /target/Crypto-Tracker-0.0.1-SNAPSHOT.jar Crypto-Tracker.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","Crypto-Tracker.jar"]